parameters:
    database:
        dsn: 'mysql:host=example.com;port=3306;dbname=LinkManager;charset=utf8mb4'
        username: 'root'
        password: ''

    timezone: 'UTC'
    display_timezone: 'UTC'

    cache:
        twig_cache_dir: 'var/cache/twig'
